Fix build error
Not sure what changed since original commit "ogre_helpers: introduce abstract
QtOgreRenderWindow class" when this was introduced.

    [...]/src/rviz/visualization_frame.cpp: In member function ‘void rviz::VisualizationFrame::initialize(const QString&)’:
    [...]/src/rviz/visualization_frame.cpp:284:67: error: invalid new-expression of abstract class type ‘rviz::QtWidgetOgreRenderWindow’
      284 |   auto render_window = new QtWidgetOgreRenderWindow(central_widget);
          |                                                                   ^
    In file included from [...]/src/rviz/visualization_frame.cpp:68:
    [...]/src/rviz/ogre_helpers/qt_widget_ogre_render_window.h:21:7: note:   because the following virtual functions are pure within ‘rviz::QtWidgetOgreRenderWindow’:
       21 | class QtWidgetOgreRenderWindow : public QWidget, public QtOgreRenderWindow
          |       ^~~~~~~~~~~~~~~~~~~~~~~~
    In file included from [...]/src/rviz/ogre_helpers/qt_widget_ogre_render_window.h:9,
                     from [...]/src/rviz/visualization_frame.cpp:68:
    [...]/src/rviz/ogre_helpers/qt_ogre_render_window.h:70:16: note: 	‘virtual void rviz::QtOgreRenderWindow::setPreRenderCallback(boost::function<void()>)’
       70 |   virtual void setPreRenderCallback(boost::function<void()> func) = 0;
          |                ^~~~~~~~~~~~~~~~~~~~
    [...]/src/rviz/ogre_helpers/qt_ogre_render_window.h:75:16: note: 	‘virtual void rviz::QtOgreRenderWindow::setPostRenderCallback(boost::function<void()>)’
       75 |   virtual void setPostRenderCallback(boost::function<void()> func) = 0;
          |                ^~~~~~~~~~~~~~~~~~~~~