Fix build error
Apparently introduced btw. 1.14.1 and 1.14.14:

    [...]/src/rviz/render_panel.cpp: In constructor ‘rviz::RenderPanel::RenderPanel(rviz::QtOgreRenderWindow*, QObject*)’:
    [...]/src/rviz/render_panel.cpp:64:3: error: ‘setFocusPolicy’ was not declared in this scope
       64 |   setFocusPolicy(Qt::WheelFocus);
          |   ^~~~~~~~~~~~~~
    [...]/src/rviz/render_panel.cpp:66:3: error: ‘setMouseTracking’ was not declared in this scope
       66 |   setMouseTracking(true);
          |   ^~~~~~~~~~~~~~~~